[project]
name = "kbm"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"

[tool.uv]
reinstall-package = ["scipath"]

[tool.uv.sources]
scipath = { git = "https://github.com/winstxnhdw/scipath" }

[dependency-groups]
dev = ["cython>=3.0.11", "matplotlib>=3.9.2", "scipath", "setuptools>=75.3.0"]

[tool.ruff]
select = ["ALL"]
ignore = ["D", "TCH", "PLR0913", "PLC0414", "PYI021"]
line-length = 120

[tool.pyright]
typeCheckingMode = "strict"
reportUnknownVariableType = false
reportUnknownMemberType = false
reportMissingTypeStubs = false
reportPrivateUsage = false

[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"
