[project]
name = "KinematicBicycleModel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
dev-dependencies = ["matplotlib>=3.9.2", "scipath"]
reinstall-package = ["scipath"]

[tool.uv.sources]
scipath = { git = "https://github.com/winstxnhdw/scipath" }

[tool.ruff]
select = ["ALL"]
ignore = ["D", "TCH", "PLR0913", "PLC0414"]
src = ["scipy"]
line-length = 120

[tool.pyright]
typeCheckingMode = "strict"
reportUnknownVariableType = false
reportUnknownMemberType = false
reportMissingTypeStubs = false
reportPrivateUsage = false
