[project]
name = "kbm"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"

[dependency-groups]
dev = [
    "cython>=3.0.11",
    "matplotlib>=3.9.2",
    "nodejs-wheel-binaries>=22.14.0",
    "pyright>=1.1.394",
    "ruff>=0.9.6",
    "scipath",
    "setuptools>=75.3.0",
]

[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"

[tool.uv]
reinstall-package = ["scipath"]

[tool.uv.sources]
scipath = { git = "https://github.com/winstxnhdw/scipath" }

[tool.ruff]
exclude = ["animate.py", "libs"]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "TC", "PLR0913", "PLC0414", "PYI021"]

[tool.pyright]
exclude = ["animate.py", "libs", ".venv"]
typeCheckingMode = "strict"
reportUnknownVariableType = false
reportUnknownMemberType = false
reportMissingTypeStubs = false
reportPrivateUsage = false
